apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/dind-cache/persistent-volume
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-pvc
  namespace: actions-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: persistent-volume-pv
---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner
  labels:
    name: actions-runner
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: persistent-volume
  namespace: actions-runner
spec:
  replicas: 1
  template:
    spec:
      repository: rhattox-helm-charts/persistent-volume
      # https://github.com/actions/actions-runner-controller/blob/master/docs/deploying-alternative-runners.md
      image: summerwind/actions-runner-dind
      dockerdWithinRunnerContainer: true
      dockerMTU: 1450
      env:
        - name: ARC_DOCKER_MTU_PROPAGATION
          value: "true"
      volumeMounts:
        - name: persistent-volume
          mountPath: /var/lib/docker
      volumes:
        - name: persistent-volume
          persistentVolumeClaim:
            claimName: persistent-volume-pvc
