name: CI
on:
  push:
    # branches:
    #   - main
    #   - feature/*
    paths-ignore:
      - .github/*
      - helm/*
      - argocd-application.yaml
      - docker-compose.yaml
      - README.md
    tags:
      - "*"
jobs:
  ci:
    uses: rhattox-shared-actions/shared-actions/.github/workflows/helm-deploy.yaml@main
    secrets:
      GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
    with:
      HELM_CHART_PATH: ./persistent-volume
